# Generated by Django 5.2.9 on 2025-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Naziv klavira', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Opis klavira', max_length=750, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PianoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategorija klavira', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PianoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tip klavira', max_length=150)),
            ],
        ),
    ]
