# Generated by Django 5.2.9 on 2025-12-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pianos.pianocategory'),
        ),
        migrations.AddField(
            model_name='piano',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='pianos.pianotype'),
        ),
    ]
