# Generated by Django 5.2.9 on 2025-12-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0002_piano_category_piano_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='piano',
            name='picture_url',
            field=models.CharField(blank=True, help_text='Upisite link do slike klavira', max_length=750, null=True),
        ),
    ]
