# Generated by Django 5.2.9 on 2025-12-04 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tip akorda', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Naziv akorda', max_length=15)),
                ('symbol', models.CharField(blank=True, help_text='Simbol akorda', max_length=15, null=True)),
                ('schema_url', models.CharField(blank=True, help_text='Putanja do sheme akorda', max_length=750, null=True)),
                ('type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='chords.chordtype')),
            ],
        ),
    ]
